# Built with Jekyll 3.6.0

# Setup
title:               benny 
tagline:             'Mayhem & Math'
description:         "Ben Chugg's corner of the interwebs, wherein he mostly messes around but sometimes does real work"
url:                 'https://benchugg.com'
baseurl:             ''

# About/contact
author:
  name: Ben Chugg
  url: https://benchugg.com
  email: ben.ih.chugg@gmail.com

twitter: 
  username: bennychugg
  card: summary

social: 
  name: Ben Chugg
  links: 
    - https://twitter.com/BennyChugg
    - https://www.linkedin.com/in/benchugg/
    - https://github.com/bchugg


# Permalinks
permalink: /:title/

# Set encoding to UTF-8
encoding: UTF-8

# Collections for texts
collections:
  research_notes:
    output: true
  writing: 
    output: true
  external_writing: 
    output: false
  papers: 
    output: false
  
# Markdown specs
markdown: kramdown

kramdown:
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  footnote_backlink: "&#x21a9;&#xfe0e;"
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  # enable_coderay: false

# Exclusions from the final site
exclude:
  - optional
  - vendor
  - ed..gemspec
  - Gemfile
  - Gemfile.lock
  - backstop_data
  - backstop.json

# Theme
# (Used for local or custom-server deployments)
# Uncomment the `theme` line if using the Ed. theme gem on your own computer or server.
# See https://jekyllrb.com/docs/themes/
# theme: "ed."

# Remote Theme
# (Used only for GitHub deployments)
# See https://help.github.com/en/articles/adding-a-jekyll-theme-to-your-github-pages-site
remote_theme: minicomp/ed

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
